### ISSUE TITLE
Open failed，something went wrong

### ISSUE THREAD

**Issue by Devil-guigui** [warsnek/for-the-king-save-editor#15]
I messed up, sorry. The following exception occurred:
System ArgumentException:已添加了具有相同键的项
E System. ThrowHelper. ThrowArgumentException(ExceptionResource
resource)
E System. Collections. Generic Dictionary 2. Insert(TKey key, TValue
value, Boolean add
在 ForTheKing Save Edit. Main Form.ctor( String save Directory Path)位置
E:\ Git-Repos\for-the-king-save-editor ForTheKing Save Edit\ Main Form.c
5:行号52
在 ForTheKingSave Edit Program. Main( Stringl args)位置
E:\Git-Repos\for-the -king-save-editor\ ForThe King Save Edit\ Program.cs
行号58

**Comment by warsnek** [comment]
My guess is that that you made a copy of the save game files inside of the savegame folder, my save game editor loads all savegames, so if you have a copy of the files in a sub folder my tool with crash because it loads a duplicate file. So move duplicate savegame files to another location outside of the savegame folder.
