### ISSUE TITLE
Error on "Enable Lore Store Options"

### ISSUE THREAD

**Issue by switchlove** [warsnek/for-the-king-save-editor#17]
Hello, 

I am trying to new 1.2.0 Save Editor and the Lore Points editor does not seem to work any longer. Adjusted the value, saved, reloaded and still the same value of Lore Points. 

Additionally I get an error when attempting to click on "Enable Lore Store Options".

![Error](https://i.imgur.com/JGXyeCU.png)

Game Version: v1.1.00.11269 epic ( Dont have the Lost Civilization Adventure Pack )
PC: Windows 10 Pro - Build 19042.804

**Comment by jiaaluo** [comment]
This issue is caused by the stats not existing in the database, you do not own the DLC and start up the game to create statistics.

**Comment by warsnek** [comment]
Yeah I should have seen that coming, I'll fix that asap so the tool still works for people without the DLC. Additionally the reason why the lore store points are not updating is probably because the Epic version has multiple profiles in the save game folder, and online and offline one an my tool is editing the wrong version for you.
Could you zip your savegame folder and upload it here so I can take a look?
 I should probably give you a selection box incase there are multiple versions of the savegame files.
 
 The savegame folder is located here: C:\Users\[UserName]\AppData\LocalLow\IronOak Games\FTK\save\

**Comment by warsnek** [comment]
I just release version 1.2.1 which might fix the issue for you it allows selection of the lore file incase there are multiple, try it out to see if that works for you!
