### ISSUE TITLE
Error on startup

### ISSUE THREAD

**Issue by EctaNeko** [warsnek/for-the-king-save-editor#8]
I get this error when i try to start the program
![Sans titre](https://user-images.githubusercontent.com/55930522/80736352-4e723080-8b12-11ea-8db1-3d4ce1a5f6c0.png)

**Comment by warsnek** [comment]
Thanks for reporting the issue, this exception happens when my tool finds multiple savegame files (*.run) files with the same name in the savegame folder. My tool also searches subdirectories! 
Did you make a backup copy in the save game location by any chance?

If you didn't do something like that, can you upload a zip of the contents of your savegame directory? You can find the save games here: "C:\Users\\[username]\AppData\LocalLow\IronOak Games\FTK\save"

**Comment by EctaNeko** [comment]
Thanks for you answer, i did made a backup folder in the save game location, i moved it and it works now!
Thank you for the help

**Comment by warsnek** [comment]
Good to hear, glad it's solved!
